### ISSUE TITLE
User Story: As a home-owner I want to remove existing kitchen units to reach a 'clean slate'

### ISSUE THREAD

**Issue by DeeMcCart** [DeeMcCart/DMC_Renovation_Tracker#1]
EPIC:  **Existing kitchen - Remove**

As a **home-owner** I can **remove existing kitchen units** so that **I'm working with a 'clean slate'**

**Acceptance Criteria**
* Kitchen units taken off walls
* Kitchen worktop removed

**Tasks**
- [x] Remove units - [ ] 
- [x] unplumb existing sink (Derek)
- [x] Remove worktop
- [x] Bring redundant units to dump
- [x] Store 'maybe keep' units elsewhere in house
![230405 Interior downstairs kitchen area](https://github.com/DeeMcCart/DMC_Renovation_Tracker/assets/126502176/5e849abe-47b2-44a1-be8b-9c770abf1588)

**Comment by DeeMcCart** [comment]
![Image](https://github.com/DeeMcCart/DMC_Renovation_Tracker/assets/126502176/9674e22e-2551-45f9-a620-3f501aad1030)
