### ISSUE TITLE
User Story: As an occupier I want to be able to open a glass back door from kitchen, directly into the back garden in order to gain more interior space and to provide a pleasant, light-filled view from the kitchen and hall

### ISSUE THREAD

**Issue by DeeMcCart** [DeeMcCart/DMC_Renovation_Tracker#10]
EPIC:  External Doors & windows - Plan

As a **occupier** I can **open a glass door from rear wall into garden** so that **I get improved light and a better traffic flow through kitchen**

**Acceptance Criteria**
* Glass back door
* Opens outwards
* Second-hand to keep costs low
* Relocated so visible from front door
* Provides extra light
* Well sealed and not draughty

**Tasks**
- [x] Source door & window (Tallaght €100, €50)
- [x] Hire van from Naas (May?)
- [x] Collect door & window (in van with Chris)
- [x] Purchase blocks, sand and plaster and other stuff (bonding agent, DPC etc)
- [x] Book 1 day of Sean's time (June)
![230405 Interior downstairs](https://github.com/DeeMcCart/DMC_Renovation_Tracker/assets/126502176/1dd1a16e-64d9-415b-8d4d-27832d3a2ccb)

**Comment by DeeMcCart** [comment]
![230505 (4)](https://github.com/DeeMcCart/DMC_Renovation_Tracker/assets/126502176/606812f6-56cc-44fa-8d1e-038c52b65ad2)
