### ISSUE TITLE
User Story: As homeowner I want to tidyup 

### ISSUE THREAD

**Issue by DeeMcCart** [DeeMcCart/DMC_Renovation_Tracker#11]
EPIC:  General

As a **homeowner** I can **tidy up** so that **I have clear visiblity of whats needed**

**Acceptance Criteria**
* House is clear of clutter and OSB sheets are removed from garden
* Waste timber and pipe insulation/ sweepings from floor removal are dumped/ burnt
*
**Tasks**
- [x] Clean blinds
- [x] Clear off OSB
- [x] Clear off waste wood to Mulligans/ Ballyogan
- [x] Make plumbing visible
- [x] Mark out stud walls
- [x] Trim overhanging tree back garden
- [x] Investigate pipework back garden

**Comment by DeeMcCart** [comment]
![230507 Sunday tidyup and remove OSB sheets (9)](https://github.com/DeeMcCart/DMC_Renovation_Tracker/assets/126502176/b7f68afe-3671-415c-9bff-084e1d5e9dda)

**Comment by DeeMcCart** [comment]
![230510 Garden wall clearance and painting (4)](https://github.com/DeeMcCart/DMC_Renovation_Tracker/assets/126502176/4f0d051f-501c-4d0e-a5a8-fad361cb5cc5)

**Comment by DeeMcCart** [comment]
![230510 Mark out stud walls (2)](https://github.com/DeeMcCart/DMC_Renovation_Tracker/assets/126502176/c7b8cc71-94a3-4e6a-9f45-36858c0bf989)

**Comment by DeeMcCart** [comment]
![230512 Fri excavating the pipe from boiler to house (1)](https://github.com/DeeMcCart/DMC_Renovation_Tracker/assets/126502176/c845d0c0-8abf-4f3e-9e3e-0c75bc3e4250)

**Comment by DeeMcCart** [comment]
![230513 Discover blocked rainwater gully rear RHS](https://github.com/DeeMcCart/DMC_Renovation_Tracker/assets/126502176/9da55793-01a8-4a58-a9d8-5cffdb5c4c56)

**Comment by DeeMcCart** [comment]
![230513 SAT Drains and lawnmowing (2)](https://github.com/DeeMcCart/DMC_Renovation_Tracker/assets/126502176/f8365b4a-8d25-4934-a3b3-ffeea381f331)
![230513 SAT Drains and lawnmowing (1)](https://github.com/DeeMcCart/DMC_Renovation_Tracker/assets/126502176/09b5971b-0b3b-46c8-a22e-f63f618d1743)

**Comment by DeeMcCart** [comment]
DONE:
Weds 10th May
Fri 12th May (visit from Mick the builder and some ideas discussed)
