### ISSUE TITLE
User Story: As a homeowner I want tomeet & Plan with plumber Darren Thompson DTNANDSON@gmail.com 23/05 to reflect new layout & proper installation, and to get a quote for same

### ISSUE THREAD

**Issue by DeeMcCart** [DeeMcCart/DMC_Renovation_Tracker#14]
EPIC:  Plumbing - Plan

As a **homeowner** I can ** plan revised pipework with plumber ** so that **to reflect new layout & proper installation**

**Acceptance Criteria**
* Planned layout for pipework is reliable for transmission of hot & cold water & central heating
* Planned layout for pipework  is consistent with new placement of radiators 
* Planned layout for pipework  allows for understairs toilet (possibly future) 
* Planned layout for pipework allows for efficient transfer of heat
* Preparation work (kango) done by homeowners to keep costs down

**Tasks**
- [x] Source plumber (Darren Thompson)
- [x] Met and surveyed the site Tuesday 23/05 11 - 1
- [x] Initial review by plumber & agree plan of action 
- [x] Deirdre/Conor/Michael/Chris to kango out agreed pipework channel to allow for 6 insulated pipes
- [x] Plumber to purchase & supply pipes, fittings and equipment

**Comment by DeeMcCart** [comment]
![230526 FRI temp kitchen part dug channel temp back bedroom temp bathroom  (4)](https://github.com/DeeMcCart/DMC_Renovation_Tracker/assets/126502176/fd4b95f8-0836-4507-b4cf-87f695223d3e)

**Comment by DeeMcCart** [comment]
![230526 FRI temp kitchen part dug channel temp back bedroom temp bathroom  (7)](https://github.com/DeeMcCart/DMC_Renovation_Tracker/assets/126502176/a89b7b56-7a16-410c-b1cb-610caf4cb5fe)
