### ISSUE TITLE
User Story: As a homeowner I can layout kitchen so that base cupboards and appliances are located in their approximate position on Sat 19th August (Deirdre)

### ISSUE THREAD

**Issue by DeeMcCart** [DeeMcCart/DMC_Renovation_Tracker#19]
EPIC:  **Kitchen - Build**

As a **homeowner** I can **layout kitchen** so that **all base cupboards and appliances are located in their approximate position**

**Acceptance Criteria**
- [x]  Base units are placed in location
- [x]  Appliances are positioned in approximate location
- [ ]  Some idea of worktop cuts to achieve best fit

**Tasks**
- [x]  Attach legs to base units (Deirdre, Sat 19th)
- [x]  Layout kitchen units in desired position (Deirdre, Sat 19th)
- [x]  Assess doors needed for desired layout and instal blanking panels where necessary
- [x]  Move fridge into longer term position

**Comment by DeeMcCart** [comment]
Done Sat 19/08

TIME TAKEN:  8 HOURS

**Comment by DeeMcCart** [comment]
![230819 Kitchen rough install (3)](https://github.com/DeeMcCart/DMC_Renovation_Tracker/assets/126502176/e4563e92-04cb-4c02-82d4-9d38a7bb7087)
![230819 Kitchen rough install (1)](https://github.com/DeeMcCart/DMC_Renovation_Tracker/assets/126502176/808646af-e157-4134-a72c-63e31f807deb)
![230819 Kitchen rough install (2)](https://github.com/DeeMcCart/DMC_Renovation_Tracker/assets/126502176/7cf8cbf4-de5d-4090-bc2c-af55808ef682)
