### ISSUE TITLE
User Story: As a homeowner I can move from PAYG electricity meter to bill-pay and get a smart plan so that I am getting electricity at the best price

### ISSUE THREAD

**Issue by DeeMcCart** [DeeMcCart/DMC_Renovation_Tracker#21]
EPIC:  **ELECTRICS**

As a **residential homeowner** I can **move from PAYG electricity meter to bill-pay and get a smart plan** so that **I am getting electricity at the best price**

**Acceptance Criteria**
- [x]  New Electric ireland account is created
- [x]  Smart billpay (free Saturdays) is activated
- [x]  Direct debit is created

**Tasks**
- [x]  Phone through to Electric Ireland and establish that the PAYG meter (MPRN 10022084177) belongs to them 
- [x]  Discuss the options for switching over to a bill pay rate
- [x]  Go online and check what bill pay options are available to me (Yessss - free wekeender plan is available, just not highly visible)
- [x]  Apply online for a new account and give all my bank and MPRN details

**Comment by DeeMcCart** [comment]
Success at second attempt (I had tried this previously but just got confused and didnt think a weekender plan was available to me).  Direct debit created under account 951489328

TIME TAKEN:  4 HOURS
