### ISSUE TITLE
User Story: Rolling Kitchen Snag List - As a resident I can complete  kitchen snags and accessorising so that the resulting kitchen is quite beautiful and pleasing to be in

### ISSUE THREAD

**Issue by DeeMcCart** [DeeMcCart/DMC_Renovation_Tracker#23]
EPIC:  **Kitchen - Finish**

As a **resident** I can **tackle kitchen snags and accessorising** so that **the resulting kitchen feels like a complete, smooth place to be in**

**Acceptance Criteria**
Kitchen appears visibly complete and fully furnished

**Tasks** (this may be a rolling list of which some get completed each week).. if so, then get stripped out of here and put into individual tasks for completion 

- [ ] Plug in cooker hood and connect to extractor vent 
- [ ] Install back window curtain for winter draught proofing/ screening
- [ ] Replace blinds over sink
- [ ] Install blinds to kitchen side window
- [ ] Finish plastering to rear of house around back door
- [x] Plaster kitchen walls
- [ ] Tile kitchen floors

**Comment by DeeMcCart** [comment]
![230827 kitchen table and accessories (1)](https://github.com/DeeMcCart/DMC_Renovation_Tracker/assets/126502176/631727a6-404a-4b0c-bb78-79c93a3c0772)
![230827 kitchen table and accessories (2)](https://github.com/DeeMcCart/DMC_Renovation_Tracker/assets/126502176/ff2274f7-1b22-4822-b17b-de61bd0e1bdc)

**Comment by DeeMcCart** [comment]
Kitchen wall plastered 23rd Sept

![Image](https://github.com/DeeMcCart/DMC_Renovation_Tracker/assets/126502176/89def39d-6aba-4058-a588-2d251af77ab2)

**Comment by DeeMcCart** [comment]
meter removed 10th October.  Touch-in painting done 27th October

![Image](https://github.com/DeeMcCart/DMC_Renovation_Tracker/assets/126502176/354dcf5b-6c4f-425e-9db3-6ca4a0534460)
![Image](https://github.com/DeeMcCart/DMC_Renovation_Tracker/assets/126502176/38448736-f7ad-4da5-a605-1cf6028a4491)
![Image](https://github.com/DeeMcCart/DMC_Renovation_Tracker/assets/126502176/ace3915a-69c7-419f-a3b4-d1bc29149b03)

**Comment by DeeMcCart** [comment]
Workaround 28/10/23:  Installed blinds to back door as a tester - good for privacy and reduces draughts, but a little large and gets in the way of the door handle and opening, e.g. trying to put christophers bike out the back gets tangled in with the blinds
