### ISSUE TITLE
User Story: Rolling Electrical Jobs:  As homeowner I want safe and secure electrical fittings in the appropriate location

### ISSUE THREAD

**Issue by DeeMcCart** [DeeMcCart/DMC_Renovation_Tracker#24]
EPIC:  ELECTRICAL - build

As a **resident** I can **safely and securely access electrical devices in the appropriate location** so that **I do not have trailing wires, unsafe or unknkown/ doubtful electrical connections in the house**

**Acceptance Criteria**
Electrical switches sockets and connections are placed in the correct locations
NOTE:  This card gets updated when tasks are assigned into sprints, the task is removed from here

**Tasks**
- [x] Add light switch for front room inside room (DONE, Oran during July)`
- [x]   Ensure existing electrical connection for boiler is disabled (DONE, Donnacha, Fri 08/09/23)
- [x]   Dig up existing red connection channel and disconnect at both ends (keep channel as this will be used for oill line to tank)
- [x]   Create new boiler electricity switch in kitchen (preferably with timer) (Switch DONE, Donnacha, Tues 05/09/23)
- [ ]   Add double socket to sitting room corner
- [x]   Add understairs light (provision for downstairs toilet) - maybe bulkhead light issue #53 
- [ ]   Move kitchen light switch from back window to adjoining hall door (could-have,, not must-have)
- [ ]  Bathroom fan/ mechanical extractor
- [ ]   Install outdoor socket
- [ ]   Install motion-activated lights to back and sides of house (?)
- [ ]   Get existing outdoor light to back of house working
- [ ]   Relocate shower power from inside bathroom to external
- [x]   Install battery-powered sensor light to hotpress
- [ ]   Install battery-powered sensor light to attic

**Comment by DeeMcCart** [comment]
CHECK WITH BRENNANS RE HEATING TIMERS
CALL DONNACHA LUNCHTIME TUESDAY
