### ISSUE TITLE
User Story: As homeowner I want to plan safe and secure electrical fittings in the appropriate location

### ISSUE THREAD

**Issue by DeeMcCart** [DeeMcCart/DMC_Renovation_Tracker#25]
EPIC:  ELECTRICAL - Plan

As a **resident** I can **safely and securely access electrical devices in the appropriate location** so that **I do not have trailing wires, unsafe or unknkown/ doubtful electrical connections in the house**

**Acceptance Criteria**
 - [x] Electrician Identified and prepared to work with me
 - [ ] Electrical switches sockets and connections are placed in the correct locations

**Tasks**
 - [ ] Source electrician part 1 (Oran, 1 day)
 - [ ] Source electrician part 2 (Owen, didn't happen)
 - [x] Source electrician part 3 (Donnacha, call him Tues morning):

- Liam 086 820 7870 Redmond just because his name doesnt begin with O
- Pat (Tinahask, better make sure thats not Ann Marie's Pat)
- Donnacha McCarthy (call him Tuesday morning; he will hopefully get one of the lads out to me during the week)

**Comment by DeeMcCart** [comment]
Electrician (Donnacha) organised and came on site Tuesday 6th September (I just missed him)
On that visit he drilled through another access for external cable for boiler (and he gave me some notes, where did I put them??)

Permanent live outside (but its not currently connected)
He also disconnected the power to the outside boiler and that is now a safe working area

Discussed double socket in sitting room (next visit)
