### ISSUE TITLE
User Story: As a partners we want to work together Sunday 27/08/23 to progress towards a finished home

### ISSUE THREAD

**Issue by DeeMcCart** [DeeMcCart/DMC_Renovation_Tracker#26]
EPIC:  **Snag list - Rolling list of tasks**

As partners Derei & Deirdre want to work together Sunday 27/08/23 to progress the renovation 

**Acceptance Criteria**
Each snag dealt with and closed off

**Tasks** (this may be a rolling list of which some get completed each week)
- [x]  Transport table to Arklow & install it (Derek, Sun 27/08/23) DONE
- [x]  Angle grinder - removed padlock to meter (Derek, Sun 27/08/23) DONE
- [x]  Angle grinder - trimmed off fitting at bottom of stairs (Derek, Sun 27/08/23) DONE
- [x]  Removed satelite dish from front of house (Derek, Sun 27/08/23) DONE
- [x]  Tightened up bolts in sofa (still 2 left that we arent sure of) (Derek, Sun 27/08/23) DONE
- [x]  Removed window beading from waste window and installed to front window (Derek, Sun 27/08/23) DONE

- [x] Moved bed in front bedroom around so head at radiator, foot at window (Deirdre, Sun 27/08/23) DONE

- [x] Stabilised and reorganised 2nd wardrobe in my room so it now holds some of the spare books (remainder under bed)
- [x] Painted door upstairs front bedroom, hotpress with first coat of marine blue cover-all paint (Deirdre, Sun 27/08/23) DONE

**Comment by DeeMcCart** [comment]
HOURS SPENT:  Derek 7; Deirdre 5
