### ISSUE TITLE
User Story: As a builder & homeowner team we give it 12 hours on Saturday 2nd Sept to see what we can accomplish

### ISSUE THREAD

**Issue by DeeMcCart** [DeeMcCart/DMC_Renovation_Tracker#27]
EPIC:  **Snag list - Rolling list of tasks** SPRINT 19 WEEK ENDING SAT 02/09/23

As a **brother and builder** I can **tackle certain snags** so that **Deirdre is happy**

**Acceptance Criteria**
Each snag dealt with and closed off

**Tasks**  (this may be a rolling list of which some get completed each week)
----
- [x]  Replace 2 kitchen sockets with USB sockets DONE Sean 02/09/23
- [x]  Tile kitchen with subway tiles (including windowsill?) in beige or green DONE Sean 02/09/23
- [x]  Install PIR lights to front of house DONE Sean 02/09/23
- [x]  Install clothes drying system under stairs (temporary ish) done Deirdre sprint 19 (clothes hangers on open stair treads)

- [x]  Clear out bathroom boxed-in redundant end-of-bath area & towel rail base DONE Deirdre 02/09/23
- [x]  Install un-needed grey 30cm base unit in space at end of bath DONE Deirdre 02/09/23
- [x]  Paint bathroom skirting and 2nd coat to windowsill DONE Deirdre 02/09/23
- [x]  Install boxed-in area at base of bath for storage DONE Deirdre 02/09/23
- [x]  Re-install sink storage cabinet as general bathroom storage  and use to hold painting materials DONE Deirdre 02/09/23
- [x]  Paint skirting Deirdre's room & 2nd coat to windowsill DONE Deirdre 02/09/23
- [x]   Clear wardrobe wood from alcove Deirdre's room and install side panels, cut wardrobe panel to make tabletop for working in alcove, install un-needed grey 30cm wall unit as under-table storage DONE Deirdre-Sean 02/09/23
- [x] Break 2 toes on left foot using bathroom cupboard shelves (OK possibly only damaged.  The foot, not the shelves)

**Comment by DeeMcCart** [comment]
![Image](https://github.com/DeeMcCart/DMC_Renovation_Tracker/assets/126502176/22fcbf23-88da-469e-b8d7-37a104ab5d68)



![Image](https://github.com/DeeMcCart/DMC_Renovation_Tracker/assets/126502176/9ce23434-850f-4b1a-9e50-13503f2621b6)



![Image](https://github.com/DeeMcCart/DMC_Renovation_Tracker/assets/126502176/6ad42556-6d75-4132-ad6e-ba4e252abcb8)



![Image](https://github.com/DeeMcCart/DMC_Renovation_Tracker/assets/126502176/f772048f-3d67-4750-9c92-69d92760ce0b)
