### ISSUE TITLE
User Story: Rolling snag list

### ISSUE THREAD

**Issue by DeeMcCart** [DeeMcCart/DMC_Renovation_Tracker#28]
EPIC:  **Snag list - Rolling list of tasks** 

As a **homeowner** I can **tackle certain snags** so that **house is increasingly liveable**

**Acceptance Criteria**
Each snag dealt with and closed off

**Tasks**  (this may be a rolling list of which some get completed each week) SPRINT20 below
----

- [x] Task  1 Fix front sensor light not working (bulb?) DONE Deirdre 03/09
- [x] Task  2 Cut in above kitchen cupboards (Deirdre)
- [ ] Task  3 Deal with small gap between doors Task #31
- [ ] Task  4 Install trim underneath cupboards
- [ ] Task  5 Install trim above cupboards
- [x] Task  6 Cut kicker boards to size Task #30
- [ ] Task  7 Finish plastering to rear of house around back door
- [x] Task  8 Reverse fridge door to open from RHS Task #29
- [ ] Task  9 Plug in cooker hood and connect to extractor vent 
- [ ] Task 10 Install back window curtain for winter draught proofing/ screening
- [ ] Task 11 Replace blinds over sink
- [ ] Task 12 Install blinks to kitchen side window
- [x] Task 13 Plaster kitchen walls
- [ ] Task 14 Tile kitchen floors
- [x] Task 15 Get superser gas heater and cylinder
- [ ] Task 16 Plan hearth (does htis require concrete base?)
- [x] Task 17 Repair concrete floors after plumbing drilling Task #50 
- [x] Task 18 Install skirting downstairs
- [ ] Task 19 downstairs - doors handles and architraves Task #51
- [ ] Task 20 upstairs - finish painting doors and doorframes & reinstall handles
- [ ] Task 21 Attempt to change outside/side passage light bulb and see if it works

**Comment by DeeMcCart** [comment]
Task18 done by Sean 28/10/23 - skirting from Arklow building supplies as Bolands were twice the price
Task19 (mostly) done by Sean 28/10/23... still have a couple of door fittings to purchase
Task 20 started by Deirdre 28,29/10/23:  first coat of paint on most door frames upstairs done (hotpress pending as ran out of paint)... still a few skirting boards to be done also.
