### ISSUE TITLE
Task:  Reverse fridge door to hang correctly

### ISSUE THREAD

**Issue by DeeMcCart** [DeeMcCart/DMC_Renovation_Tracker#29]
EPIC:  **Kitchen - Finish**

**Acceptance Criteria**
Fridge door 

**Tasks** (this may be a rolling list of which some get completed each week)
- [x] Task : Reverse fridge door to open from RHS
- [x] Empty out the fridge
- [x] lay it on its back
- [x] find the effing user manual where it explained how to do this
- [x] do the switcheroo

**Comment by DeeMcCart** [comment]
Never found the effing manual so thank jaysus Sean did this 28/10/23:


![Image](https://github.com/DeeMcCart/DMC_Renovation_Tracker/assets/126502176/7d91bacb-bbff-4848-a1dc-7767819ba460)
