### ISSUE TITLE
User Story: As a home-owner I want to remove existing kitchen appliances to reach a 'clean slate'

### ISSUE THREAD

**Issue by DeeMcCart** [DeeMcCart/DMC_Renovation_Tracker#3]
`EPIC:`  **Existing kitchen - Remove**

As a **home-owner** I can **remove existing kitchen appliances** so that **I reach a 'clean slate'**

**Acceptance Criteria**
* Kitchen appliances removed

**Tasks**
- [x]  2 x fridge freezer to recycling 
- [x] : cooker to recycling 
- [x]  washing machine to recycling

**Comment by DeeMcCart** [comment]
![230430 SUN strip laminate floor (1)](https://github.com/DeeMcCart/DMC_Renovation_Tracker/assets/126502176/70a45981-ed0d-4e6b-95fc-0c50485a39cb)
