### ISSUE TITLE
Task:  Install kitchen kicker boards

### ISSUE THREAD

**Issue by DeeMcCart** [DeeMcCart/DMC_Renovation_Tracker#30]
EPIC:  **Kitchen - Finish** 

**Acceptance Criteria**
- [ ] Jigsaw tested and proven for future use
- [ ] Kicker boards cut to size and installed in kitchen

**Tasks**  (this may be a rolling list of which some get completed each week) SPRINT21 below
----
- [ ] Task: Unpackage new jigsaw and read instructions
- [x] Cut kicker boards to size
- [x] Brace kicker boards, either against unit legs or against one another

**Comment by DeeMcCart** [comment]
Done 28/10/23 by Sean - loose fitted as these may need to be adjusted when tiled floor is installed.
Finally - I can get rid of spare kicker board!!!

![Image](https://github.com/DeeMcCart/DMC_Renovation_Tracker/assets/126502176/39336144-ea5d-418e-9255-15aaa276d1b4)
