### ISSUE TITLE
Tasks: Electrical Jobs Sat 2nd Sept (Sean)

### ISSUE THREAD

**Issue by DeeMcCart** [DeeMcCart/DMC_Renovation_Tracker#33]
EPIC:  ELECTRICAL - build

As a **resident** I can **safely and securely access electrical devices in the appropriate location** so that **I do not have trailing wires, unsafe or unknkown/ doubtful electrical connections in the house**

**Acceptance Criteria**
Electrical switches sockets and connections are placed in the correct locations

**Tasks**
- [x]   Replace 2 of the kitchen sockets with USB sockets to allow charging points  (DONE, Sean Saturday 02/09/23)
- [x]   Replace front outdoor light fitting with motion-activated LED fitting (DONE, Sean Saturday 02/09/23)
- [x]   Bathroom shower power - replace switch with cord (DONE, Sean Saturday 02/09/23)
