### ISSUE TITLE
Task:  Disconnect existing boiler and providing wiring for boiler in new location (Donnacha McCarthy)

### ISSUE THREAD

**Issue by DeeMcCart** [DeeMcCart/DMC_Renovation_Tracker#34]
EPIC:  ELECTRICAL - build

**Acceptance Criteria**
Electrical switches sockets and connections are placed in the correct locations

**Tasks**
- [x]   Ensure existing electrical connection for boiler is disabled (DONE, Donnacha, Thurs 07/09/23)
- [x]   Create new boiler electricity switch in kitchen (preferably with timer) (Switch DONE, Donnacha, Tues 05/09/23)
- [X]   Discuss boiler timer options
- [x]   Install battery-powered sensor light to hotpress - DONE - Deirdre (sensor isnt great)
