### ISSUE TITLE
Task: Followup on removal of PAYG smart meters - Electric Ireland/ KN Networks

### ISSUE THREAD

**Issue by DeeMcCart** [DeeMcCart/DMC_Renovation_Tracker#35]
EPIC:  **ELECTRICS**

As a **residential homeowner** I can **deactivate and remove existing electricity PAYG meters** so that **remove confusing electrics, improve aesthetics and re-use the wall space**

**Acceptance Criteria**

**Tasks**
- [x]  Contact Electric Ireland PAYG team to follow-up on removal of meters requested on 16/08/23
- [x] Update my mobile number witht Electric Ireland to tesco mobile number
- [x] Create new request for KN Networks with new mobile number as previous request was closed when they couldnt reach me on my old mobile phone #.
- [x] Await reply and schedule for follow-up 2 weeks (Electric Ireland said I should have follow-on within 2-3 weeks)

MPRN 10022084177
(existing serial number H17P1112366)

![Coin Meter](https://github.com/DeeMcCart/DMC_Renovation_Tracker/assets/126502176/341333a2-98e9-4d3a-9fc4-ca57df5c1006)
meter is removed by Electrician or KN Networks 
![Location of meters](https://github.com/DeeMcCart/DMC_Renovation_Tracker/assets/126502176/f89070f0-d42b-4111-ad44-6a2d1a3702be)

**Comment by DeeMcCart** [comment]
Phone call 25/09 to book removal - settled for Tuesday 3rd October p.m.

**Comment by DeeMcCart** [comment]
This removal eventually done october 10th, and thankfully both meters were removed!


![Image](https://github.com/DeeMcCart/DMC_Renovation_Tracker/assets/126502176/e712832a-7170-49c6-b8f1-74e6a074e40d)
