### ISSUE TITLE
Task: Followup on removal of PAYG smart meters - Electric Ireland/ KN Networks

### ISSUE THREAD

**Issue by DeeMcCart** [DeeMcCart/DMC_Renovation_Tracker#36]
EPIC:  **ELECTRICS**

As a **residential homeowner** I can **deactivate and remove existing electricity PAYG meters** so that **remove confusing electrics, improve aesthetics and re-use the wall space**

**Acceptance Criteria**

**Tasks**
- [x]  Contact Electric Ireland PAYG team to follow-up on removal of meters requested on 16/08/23
- [x] Follow-up on new request 14/09/23 for KN Networks with new mobile number 
- [x] If no appointment, schedule for follow-up 1 weeks 

MPRN 10022084177
(existing serial number H17P1112366)

![Coin Meter](https://github.com/DeeMcCart/DMC_Renovation_Tracker/assets/126502176/341333a2-98e9-4d3a-9fc4-ca57df5c1006)
meter is removed by Electrician or KN Networks 
![Location of meters](https://github.com/DeeMcCart/DMC_Renovation_Tracker/assets/126502176/f89070f0-d42b-4111-ad44-6a2d1a3702be)

**Comment by DeeMcCart** [comment]
Finally done 10/10/23 ref issue #35
