### ISSUE TITLE
User Story: As renovator I want to develop a masterplan so that things happen in logical sequence

### ISSUE THREAD

**Issue by DeeMcCart** [DeeMcCart/DMC_Renovation_Tracker#37]
EPIC:  <epic>

As a **role** I can **capability** so that **received benefit**
Assumptions:  

**Acceptance Criteria**
- An outline plan is prepared
- Which although not absolutely tied to dates, has a good idea of sequencing and dependencies

**Tasks**
- [x]  Choose a day for planning (Sunday 14th May)
- [x]  Determine what needs to be done
- [ ]  Determine priorities 
- [ ]  Determine sequencing and resources needed for each task

**Comment by DeeMcCart** [comment]
Priorities determined on the day and activities were (Deirdre makes plans and God laughs loudly):
1. Clear out gully
2. Locate existing sewer manhole (existing vent at middle of house might be radon rather than sewer)
3. Determine existing piplework
4. Determine required levels and purchase door and sidelight for back window/door swoperoo
5. Plumber
6. Remove hearth
7. Floor insulation - plan it - source it - plan for insulation
8. Consider heating systems

**Comment by DeeMcCart** [comment]
PRIORITIES (Fri 19th/ Sat 20th):
1. find a fecking plumber - this is absolutely most important thing now.  Idealy to play pipework week of Mon 22nd May
2. find a floor screeding company - ideally to lay floor week of Mon 29th May
3. Agree on a back door (750 for glass door, outward opening from PVC Mikes/ uFit PVC) - checked Fri 19th May
4. Sean to fit back door weekend of 5th June .... possibly attic oor also?
5. can then look at getting stud walls done
6. plus new front door

Small jobs for me:
* continue to investigate pipework/ sewerage network
* paint ceiling downstoars
* paint front bedroom upstairs (including woodwork)
* shower hanging rail for bathroom?
