### ISSUE TITLE
Task:  Get Insulation Quote (A Rate Your Attic)  

### ISSUE THREAD

**Issue by DeeMcCart** [DeeMcCart/DMC_Renovation_Tracker#39]
EPIC:  <epic>

As a **role** I can **capability** so that **received benefit**
Assumptions:  

**Acceptance Criteria**
* Have quote from contractors
* Make decision whether to proceed

**Tasks**
- [x] Quote was given surprisingly quickly, next day appointment for a dublin company
- [x] Ben Kavanagh - seemed very nice indeed - 
- [x] Quotes are pricey - Attic 1825 minus 1500 grant = 325.  1825 payable on completion, of which 1500 is redeemable
- [x] BER 260 less 100 = 160
- [x] Cavity wall insulation 2920 less SEAI grant 1500 less discount 150 - 2770 payable on completion, of which 1500 is redeemable

4805 payable now, of which 3050 is reclaimable.... so net cost 1755 for walls and attic (and a bit of lost cashflow while awaiting for grant)

**Comment by DeeMcCart** [comment]
Decided not to make a decision just yet, I was a bit uneasy at payment up front as it was a large investment
Also a bit uneasy that they seemed to be taking a big interest in me and chasing me for a decision
