### ISSUE TITLE
User Story: As home-owner I want to remove sections of raised wooden sub-floor under kitchen to investigate rodent ingress

### ISSUE THREAD

**Issue by DeeMcCart** [DeeMcCart/DMC_Renovation_Tracker#4]
EPIC:  Existing subfloor - Remove

As a **home-owner** I can **investigate rodent infestation under kitchen subfloor** so that **I can determine if historical or current**

**Acceptance Criteria**
Damaged OSB subfloor is lifted under kitchen area
Evidence of rodents is traced to source
Floor is kept clear and hoovered at each stage of removal

**Tasks**
- [x] Remove first section of laminate flooring (Fri 28/04)
- [x] Trial use of tools(crowbar, shovels) to lever up floor sheets
- [x] Remove OSB subfloor part 1 kitchen area (Deirdre)

![230429 Start lifting floor](https://github.com/DeeMcCart/DMC_Renovation_Tracker/assets/126502176/d8d12332-78da-44a8-bcf2-55044da220d5)

**Comment by DeeMcCart** [comment]
Discovered big gaping hole in back wa
![230430 Start lifting floor and discovering horrors (1)](https://github.com/DeeMcCart/DMC_Renovation_Tracker/assets/126502176/9cf35ac7-8b25-429b-ad3e-18255a2d3dda)
ll
