### ISSUE TITLE
User Story: Purchase what's needed for now

### ISSUE THREAD

**Issue by DeeMcCart** [DeeMcCart/DMC_Renovation_Tracker#40]
EPIC:  <epic>

As a **role** I can **capability** so that **received benefit**
Assumptions:  

**Acceptance Criteria**
* Shower rail
*  Fireplace & hearth (Jobstown)
* Back door and side window
* Shower curtain
* Basin and undercounter cupboard for bathroom
* Folding attic ladder (Kill, Kildare) - collected Thurs 25th May (sprint05)
* A different insulation quote - requested from Carlow insulation - done Sat 27th May (sprint05) - 680 cost as they are one-stop-shop
*
**Tasks**
- [x] Go to tallaght and collect hearth and fireback & fire bricks 
- [x] Sean to collect fire surround from Jobstown at weekend - he is working in the area
- [x]  Hunt around for shower rail solution (eventually found in JYSK)
- [X ] Hunt around for back door - considering PVC Mike's new glass door for €750; eventually decided to use the glass back door and window already purchased at the start of project.  Door is a little narrow, but it is full glass and it DOES open outwards.... handiest just to stick with these.
- [X ] Got basic fittings for bathroom
-
