### ISSUE TITLE
User Story: As an occupier I would like a usable bathroom (that doesnt fecking blind me with cringe and filth)

### ISSUE THREAD

**Issue by DeeMcCart** [DeeMcCart/DMC_Renovation_Tracker#41]
EPIC:  BATHROOM

As a **role** I can **capability** so that **received benefit**
Assumptions:  
* Existing plumbing to sink and toilet still working#
* Shower still functional and will heat water

**Acceptance Criteria**
- Functional bathroom which is clean 
- and reasonably pleasant in appearance

**Tasks**
- [x] Remove glass door shower surround
- [x] Clar off (most of) MASTIC ON TILES
- [x] scrape tiles clean
- [x] remove fittings over bath
- [x] remove tile around bath
- [x] remove tiles over sink
- [x] paint (most of) walls magnolia
- [x] remove door handles so door is ready for painting

**Comment by DeeMcCart** [comment]
![230522 MON tile paint bathroom (3)](https://github.com/DeeMcCart/DMC_Renovation_Tracker/assets/126502176/efa6ff92-baa4-4621-92c5-c603b6a0a525)
![230522 MON tile paint bathroom (1)](https://github.com/DeeMcCart/DMC_Renovation_Tracker/assets/126502176/1ce70426-1fce-4ea1-ab77-405654d8a0be)
![230522 MON tile paint bathroom (2)](https://github.com/DeeMcCart/DMC_Renovation_Tracker/assets/126502176/a0de45d7-365a-4897-8aa6-34e029708043)
