### ISSUE TITLE
User Story:  As home owner I want to paint **Upstairs Front Bedroom** magnolia, for cleanliness and consistency

### ISSUE THREAD

**Issue by DeeMcCart** [DeeMcCart/DMC_Renovation_Tracker#42]
EPIC:  PAINTING

Assumptions:  
* The walls are generally in good nick just need to be freshened up
*
**Acceptance Criteria**
- Front room upstairs ceiling painted
- Front room upstairs walls painted magnolia

**Tasks**
- [x] Move some of the stored doors (double doors for downstairs, plus glass panelled doors for hall and sitting room) out into hall (or somewhere else)
- [x]  Clear and dust and remove cobwebs and contents of room
- [x]  Paint ceiling white
- [x]  touch in magnolia
- [x] paint walls magnolia coat 1
- [x] paint walls magolia coat 2
 DONE - Sun, 21 Mon 22 & Tues 23rd May
