### ISSUE TITLE
User Story:  As home owner I want to setup **Upstairs Front Bedroom** as temporary kitchen, for Chris use end May 

### ISSUE THREAD

**Issue by DeeMcCart** [DeeMcCart/DMC_Renovation_Tracker#43]
EPIC:  KITCHEN

Assumptions:  
* Units are mostly stored in back bedroom right now
* Front room has been painted this week

**Acceptance Criteria**
- Kitchen assembled and usable () in upstairs front room
- Temporary kitchen has food storage, kettle and toaster and microwave for essential user

**Tasks**
- [x] Move base units from back bedroom into front bedroom
- [X]  Position base units into some sort of arrangement that makes sense
- [x]  Add fitted kitchen door hinges and doors to base units
- [x] 'Install' some top cupbarods (with doors where possible)
- [x] Move remainder of kitchen from back bedroom and stack into front room
- [x] Bring large 8' wood effect panel from Carlow to use as temporary worktop
- [x] Move heavy worktops to back garden, under tarpaulin
 DONE - Weds 24th, Thurs 25th May

**Comment by DeeMcCart** [comment]
![230526 FRI temp kitchen part dug channel temp back bedroom temp bathroom  (3)](https://github.com/DeeMcCart/DMC_Renovation_Tracker/assets/126502176/ca9abb4d-8b1e-4d92-a7b1-ec4f553068a3)
![230524 WEDS start with temp kitchen start with digging channel (2)](https://github.com/DeeMcCart/DMC_Renovation_Tracker/assets/126502176/f2440b70-f839-4098-ae10-f88e05a1e7a3)
![230526 FRI temp kitchen part dug channel temp back bedroom temp bathroom  (2)](https://github.com/DeeMcCart/DMC_Renovation_Tracker/assets/126502176/61ae5191-9ed3-428c-83d7-2d45568ab139)

**Comment by DeeMcCart** [comment]
![230526 FRI temp kitchen part dug channel temp back bedroom temp bathroom  (19)](https://github.com/DeeMcCart/DMC_Renovation_Tracker/assets/126502176/076e2ef2-17d5-409a-b750-f38f5eb2f147)
