### ISSUE TITLE
User Story:  As homeowner I want to get a quote from Superior Floor Screed re level concrete floor entire downstairs 

### ISSUE THREAD

**Issue by DeeMcCart** [DeeMcCart/DMC_Renovation_Tracker#44]
EPIC:  FLOR

As a **role** I can **capability** so that **received benefit**
Assumptions:  

**Acceptance Criteria**
- Get a quote
- Get agreement as to what the job involves

**Tasks**
- [x] Meet with superior floor screed in Arklow (they were at a different house and I noticed them on the aughtim arklow road and gave them a bell.  Well, kind of followed them around the town up towards Abbeylands
- [x]  Barry came to house and did a survey and took levels.  Approx 8cm at back 5cm at front.
- [x]  Explained the plan re trench for pipes etc
- [ ] All done Thurs 25th May
