### ISSUE TITLE
User Story: As homeowner I want to paint **downstairs** magnolia for cleanliness and consistency

### ISSUE THREAD

**Issue by DeeMcCart** [DeeMcCart/DMC_Renovation_Tracker#45]
As a **role** I can **capability** so that **received benefit**
Assumptions:  
Kitchen units gone from downstairs

**Acceptance Criteria**
- First coat magnolia done.  
- Horrible dark brown feature walls downstairs painted over
- Ceiling paint first coat
- Water stains in ceiling reduced in visibility

**Tasks**
- [x] Paint ceiling white (I assume I did this anyway) 
- [x] Paint walls magnolia first coat 
- [x] Try the stain blocker paint on tricky parts of the ceiling

**Comment by DeeMcCart** [comment]
Did this (a long time ago).  Should have a follow-on task for completing the cutting in.  closing it anyway
