### ISSUE TITLE
User Story: As  homeowner/project manager I want to have the walls plastered Sat 16/09 (Sean) so I can progress with plumbing

### ISSUE THREAD

**Issue by DeeMcCart** [DeeMcCart/DMC_Renovation_Tracker#47]
EPIC:  GENERAL

As a **role** I can **capability** so that **received benefit**
Assumptions:  
Stud walls done

**Acceptance Criteria**
Sittingroom space for new socket with wiring through stud wall
Sittingroom fully plasterboarded and plastered
Hallway fully plasterboarded and plastered
Kitchen fully plasterboarded and plastered 
(Note there is a follow-on task to replace the doors - later - after drying)
Furniture replaced in room - spaced from wall to allow drying space
**Tasks**
- [x] Bolands - buy 1 sheet plasterboard; scrim and skimcoat x 3 bags (Deirdre)
- [x] Brennans - buy 6m 2.5 something and earth cable (Deirdre)
- [x] Wire between junction and socket (Sean)
- [x] remove double doors, kitchen and sittingroom doors (Sean)
- [x] finish plasterboarding in sitting room' (Sean)
- [x] plaster sitting room (both walls) (Sean)
- [x] finish plasterboarding in hall (Sean)
- [x] plaster hall (Sean)
- [x] finish plasterboarding in kitchen (Sean)
- [x] plaster kitchen (Sean)
- [x] Cleanup (Seanm then Deirdre)
- [x] Replace furniture in room (Deirdre)
- [x] 3 days drying (mother nature)

**Comment by DeeMcCart** [comment]
All done 16/09/23.  Note follow-on tasks

**Comment by DeeMcCart** [comment]
Completed (picutres to follow)
