### ISSUE TITLE
User Story: As a homeowner I want reliable and attractive firepace stove display to heat downstairs 2 rooms and add to attractiveness

### ISSUE THREAD

**Issue by DeeMcCart** [DeeMcCart/DMC_Renovation_Tracker#48]
EPIC:  STOVE

As a **role** I can **capability** so that **received benefit**
Assumptions:  
Probably going for stove
**Acceptance Criteria**
Decision made re stove

**Tasks**
- [x] Prepare mockup of fireplace layout (Deirdre prior to 11am)
- [x] John Byrne to visit Friday 1t5/09/23 and assess/ recommend (JOhn Byrne, 11am Friday)
- [ ] Review recommendations and make decision (Deirdre)
