### ISSUE TITLE
Task:  Plaster sittingroom, hall and kitchen stud walls (Sean, Saturday 16/09/23)

### ISSUE THREAD

**Issue by DeeMcCart** [DeeMcCart/DMC_Renovation_Tracker#49]
EPIC:  <epic>

As a **role** I can **capability** so that **received benefit**
Assumptions:  
(it has emerged that) plastering walls is required before heating can be installed/ comissioned

**Acceptance Criteria**
Remaining plasterboard installed
Sitting room 2 walls plastered
Hall 1 wall plastered
Kitchen 1 wall plastered

**Tasks**

** Pre-requisites (Deirdre):
- [x] Move all sitting room & kitchen furniture and flooring for plastering
- [x] Purchase 3 bags skimcoat, scrim tape, 1 sheet plasterboard (split for transport)
- [x] Purchase cable from Brennans electrical 

** Plastering tasks (Sean):
- [x] Remove plasterboard & Thread cable through stud walls to corner of sittingroom
- [x] Fit remaining plasterboard to stud walls 
- [x] tap down plasterboard screws
- [x] remove doors
- [x] plaster sittingroom
- [x] plaster hall
- [x] plaster kitchen
- [x] clean up

** Follow-up (Deirdre):
- [x] Clear off floors (as best as possible)
- [x] Reinstate sitting room & kitchen furniture & flooring
- [x] Clean up
.... then allow 3 days to dry

**Comment by DeeMcCart** [comment]
Jobs done, photos to follow
