### ISSUE TITLE
User Story: As a home-owner I can remove first third of subfloor so that floor levels and issues with rodents/water/levels can be seen

### ISSUE THREAD

**Issue by DeeMcCart** [DeeMcCart/DMC_Renovation_Tracker#5]
EPIC:  Existing subfloor - Remove

As a **home-owner** I can **remove first third of subfloor** so that **possible leaks can be investigated and plumbing/levels can be seen**

**Acceptance Criteria**
* Existing OSB subfloor - mid section is removed 
* Existing ground-floor plumbing is increasingly exposed and any leaks can be seen (front of fireplace)
* Existing ground-floor levels (e.g. drop at inwards-opening back & front doors) are increasingly visible 
* Floor is kept clear and hoovered at each stage of removal

**Tasks**
- [x] Remove laminate floor (Deirdre, Sun 30/04)
- [x] Remove OSB subfloor part 1 kitchen area (Conor & Michael Mon 01/05)
- [x] Perfect use of tools(crowbar, shovels) to lever up floor sheets
- [x] Move sheets to outside house

**Comment by DeeMcCart** [comment]
![230501 first third of floor up conor and michael](https://github.com/DeeMcCart/DMC_Renovation_Tracker/assets/126502176/fab2d133-f44b-4cb1-bcf2-228ecaf93b73)

**Comment by DeeMcCart** [comment]
![230501 first third of floor up conor and michael](https://github.com/DeeMcCart/DMC_Renovation_Tracker/assets/126502176/2a42077f-4586-4c25-aeed-52d9d912bf36)

**Comment by DeeMcCart** [comment]
![Image](https://github.com/DeeMcCart/DMC_Renovation_Tracker/assets/126502176/67caf357-ab79-4f5d-957a-10a1c8721705)

**Comment by DeeMcCart** [comment]
![Image](https://github.com/DeeMcCart/DMC_Renovation_Tracker/assets/126502176/6a68a451-01ff-45b9-a3d0-fe2dcde40178)
