### ISSUE TITLE
Task:  Repair concrete floors after plumbing work

### ISSUE THREAD

**Issue by DeeMcCart** [DeeMcCart/DMC_Renovation_Tracker#50]
EPIC:  <epic>

As a **role** I can **capability** so that **received benefit**
Assumptions:  

**Acceptance Criteria**
* Behind sofa level
* Behind TV level
* Underneath fridge level

**Tasks**
- [x] Mix up concrete 3:1 in pourable bucket
- [x] Pour into floor area underneath fridge
- [x] Pour into floor area behind sofa
- [x] Pour into floor area behind TV
- [x] Give 24 hours to dry
- [x] Apply levelling compound

**Comment by DeeMcCart** [comment]
Concrete Done Thurs 26/10/23 Chris and Deirdre.
However levelling compound still to follow

![Image](https://github.com/DeeMcCart/DMC_Renovation_Tracker/assets/126502176/7f6cfc69-578d-4685-a80b-1106efe9929a)

**Comment by DeeMcCart** [comment]
Did levelling compound first week of December 2023.
Task now fully complete
