### ISSUE TITLE
Task:  Re-Hang Doors after plastering completed, add door stops and architraves

### ISSUE THREAD

**Issue by DeeMcCart** [DeeMcCart/DMC_Renovation_Tracker#51]
EPIC:  DOORS

As a **role** I can **capability** so that **received benefit**
Assumptions:  

**Acceptance Criteria**
* All doors open and close
* Doors have handles
* Door stops in place
* Door surrounds and architraves

**Tasks**
- [x] Re-hang hall-> kitchen door, hall -> sittingrom door, and sittingroom -> kitchen double doors
- [x] Handle for hall-> kitchen door 
- [ ] Receiver for hall-> kitchen door
- [x] Architrave for interior (kitchen side) hall-> kitchen door

- [x] Re-hang hall-> sittingroom door
- [x] Handle for hall-> sittingroom door 
- [x] Receiver for hall-> sittingroom
- [x] Architrave for exterior (hall side) hall-> sittingroom door
- [x] Architrave for interior (sittingroom side) hall-> sittingroom door

- [x] Re-hang sittingroom door -> kitchen double doors
- [x] Plane doors to close in middle
- [x] Plane doors to close in middle
- [ ] Architrave for exterior (sittingroom side ) sittingroom -> kitchen doors
- [ ] Architrave for interior (kitchen side) sittingroom -> kitchen doors

- [x] Source door for downstairs cloakroom
- [x] Hang hall-> cloakroom door issue #53 
- [x] Handle for hall-> cloakroom door issue #53 
- [x] Receiver for hall-> cloakroom issue #53 
- [ ] Architrave for exterior (hall side) hall-> cloakroom
- [ ] Complete interior plasterboarding & architrave cloakroom

UPSTAIRS DOORs - separate task

**Comment by DeeMcCart** [comment]
Derek came over Friday 11/10/23 and he hung doors with my help
Sean 28/10/23 corrected the double doors so they now close (planed close to 3/4 inch off left hand frame from kitchen side)
Visually they look right.
2 doors from hall to kitchen and sitting room checked for alignment and door stops and archictraves mostly installed (not hall -> kitvhen as need to see how this will work with cloakroom door),



![Image](https://github.com/DeeMcCart/DMC_Renovation_Tracker/assets/126502176/2dd5e838-cbb9-4906-8e20-2524ba22a660)
![Image](https://github.com/DeeMcCart/DMC_Renovation_Tracker/assets/126502176/9c60790a-a215-4335-8064-3c9fd606019a)
![Image](https://github.com/DeeMcCart/DMC_Renovation_Tracker/assets/126502176/22edbbe6-3257-4019-871a-eb06944b4e37)
![Image](https://github.com/DeeMcCart/DMC_Renovation_Tracker/assets/126502176/d3de8bce-8dcb-42ea-a2f4-420dd1e02fad)

**Comment by DeeMcCart** [comment]
Door sourced for downstairs cloakroom 19/12/23
Door installed Thurs 21/12/23 as part of cloakroom tiling etc
