### ISSUE TITLE
Task:  re-hang side gate so it opens fully

### ISSUE THREAD

**Issue by DeeMcCart** [DeeMcCart/DMC_Renovation_Tracker#52]
EPIC:  **Cloakroom - Finish**

As a **resident** I can **open the side gate fully** so that **large items can be moved in and out through the side of the house**

**Acceptance Criteria**
* Side gate opens fully (since cloakroom installed there is some pipework blocking the gate
* 
**Tasks** (this may be a rolling list of which some get completed each week).. if so, then get stripped out of here and put into individual tasks for completion 

- [ ] remove timber facing
- [ ] lift gate off current supports
- [ ] possibly temporary fix to open outwards rather than inwards
- [ ] move fixings to next concrete post.
- [ ] Re-position the gate to open inswards at new location

**Comment by DeeMcCart** [comment]
Note - purchased new (more beautiful) wooden side gate 19/11/23, consider using this whenever Sean gets a chance to return
