### ISSUE TITLE
User Story:  As homeowner I would like a pleasant functional understairs toilet & sink to facilitate visitors & provide secondary toilet

### ISSUE THREAD

**Issue by DeeMcCart** [DeeMcCart/DMC_Renovation_Tracker#53]
EPIC:  <epic>

As a **homeowner** I can **access alternative toilet and sink downstairs** so that **visitors can use the bathroom without going upstairs, and a secondary toilet is available when the main bathroom is occupied**

Assumptions:  
Sufficient headroom understairs
Plumbing is feasible

**Acceptance Criteria**
- [ ] Understairs bathroom constructed with privacy
- [ ] Sink and small undersink cabinet for storage
- [ ] Neat toilet
- [ ] Hot and cold water to sink
- [ ] Sewerage piping is adequate to facilitate flow and prevent blockage
- [ ] toilet is fitted with integral seat and lid
- [ ] Room is tiled walls and floor
- [ ] Mirror is installed
- [ ] Wall hooks for towel installed
- [ ] Wall holder for loo roll installed
- [ ] Ceiling and walls sanded and painted

**Tasks**
- [ ] Frame out room
- [ ] Purchase toilet and cabinet unit 
- [ ] Install pipework
- [ ] Install toilet and sink
- [ ] Install temporary privacy solution (curtain)
- [ ] Plasterboard out remainder of room
- [ ] Box over pipework
- [ ] Source tiles
- [ ] Tile out interior
- [ ] Install door, handle & receiver
- [ ] Install architrave - interior
- [ ] Install architrave - hall side
