### ISSUE TITLE
User Story: As homeowner I can remove mid section of floor so that issues with plumbing/leaks/floor levels can be seen

### ISSUE THREAD

**Issue by DeeMcCart** [DeeMcCart/DMC_Renovation_Tracker#6]
EPIC:  <epic>

As a **homeowner** I can **remove mid section of floor ** so that **issues with plumbing/leaks/floor levels can be seen**

**Acceptance Criteria**
* Existing OSB subfloor - mid section is removed 
* Existing ground-floor plumbing is exposed and any leaks can be seen 
* Existing ground-floor levels (e.g. drop at inwards-opening back & front doors) are clearly visible 
* Plumbing leak in front of fireplace is resolved
* Floor is kept clear and hoovered at each stage of removal

**Tasks**
- [x] Strip remainder laminate floor (Deirdre)
- [x] Remove OSB mid area (Deirdre)
- [x] Move sheets to outside house and cut down where possible
- [x] Repair plumbing leak in front of fireplace (Derek)
- [x] Transport sheets offsite (Carlow / dump/ eventually Donals garage)

**Comment by DeeMcCart** [comment]
![230430 SUN strip laminate floor (4)](https://github.com/DeeMcCart/DMC_Renovation_Tracker/assets/126502176/a91ca621-3c7e-4c7c-8b7b-cd2c7e3c9039)

**Comment by DeeMcCart** [comment]
![230430 Start lifting floor and discovering horrors (2)](https://github.com/DeeMcCart/DMC_Renovation_Tracker/assets/126502176/f4e34970-b4e2-484f-9024-21e5294b2dc7)

**Comment by DeeMcCart** [comment]
![230503 WEDS another one third floor lifted (1)](https://github.com/DeeMcCart/DMC_Renovation_Tracker/assets/126502176/b3ac49e9-e122-4690-9cf8-e8a9322783b5)

**Comment by DeeMcCart** [comment]
![230503 second third of floor up Deirdre (2)](https://github.com/DeeMcCart/DMC_Renovation_Tracker/assets/126502176/437a398d-3c50-42f3-a5c5-b704a72fbdb2)

**Comment by DeeMcCart** [comment]
![Image](https://github.com/DeeMcCart/DMC_Renovation_Tracker/assets/126502176/b66beb0f-2e27-45ef-9e3c-ddd181f969a0)
