### ISSUE TITLE
User Story: As home-owner I want to remove remaining sections of raised wooden to reach consistent floorbase

### ISSUE THREAD

**Issue by DeeMcCart** [DeeMcCart/DMC_Renovation_Tracker#7]
EPIC:  Existing subfloor - Remove

As a **home-owner** I can **remove remaining sections of raised wooden floor** so that **expose consistent floorbase with clear visibility of plumbing**

**Acceptance Criteria**
* Existing OSB subfloor - front section is removed 
* Existing ground-floor plumbing is exposed and any leaks can be seen 
* Existing ground-floor levels (e.g. drop at inwards-opening back & front doors) are clearly visible 
* Floor is kept clear and hoovered at each stage of removal

**Tasks**
- [x] Remove OSB subfloor front area (Deirdre)
- [x] Move sheets to outside house and cut down where possible
- [x] Transport sheets offsite (Carlow / dump/ eventually Donals garage)

**Comment by DeeMcCart** [comment]
![230505 last third of floor mostly up Deirdre (1)](https://github.com/DeeMcCart/DMC_Renovation_Tracker/assets/126502176/8ec60848-c004-47ec-8dac-e880fa76045a)

**Comment by DeeMcCart** [comment]
![230505 last third of floor mostly up Deirdre (2)](https://github.com/DeeMcCart/DMC_Renovation_Tracker/assets/126502176/d8c7b57c-cded-4d5f-9225-9ab7e15b6aea)
