### ISSUE TITLE
User Story: As homeowner I wish to have a bright and fully functional kitchen which will allow me to relax and do whatever household tasks needed

### ISSUE THREAD

**Issue by DeeMcCart** [DeeMcCart/DMC_Renovation_Tracker#9]
EPIC:  New kitchen - Plan

As a **homeowner ** I can **have a bright and fully functional kitchen** so that **relax and do whatever household tasks needed**

**Acceptance Criteria**
* Replacement kitchen sourced
* Replacement kitchen brought to house
* Replacement kitchen stored in weather-safe space while downstairs floor refitted

**Tasks**
- [x] Sketch out approximate sizing for kitchen
- [x] Source replacement kitchen (Swords, €900)
- [x] Hire van (Naas, 29/04/23)
- [x] Travel to swords for first kitchen load (Swords, Sat 29/04)
- [x] Drive to Arklow & unload with Michael/ Sean
- [x] Travel to swords & meet Derek there for disconnection of plumbing and second kitchen load (Swords, Sat 30/04)
- [x] Drive to Arklow & unload (with help of next door neighbour Eamonn)
- [x] Move units upstairs to back bedroom for storage until floor done downstairs
- [x] Mo- [ ] ve worktops to back garden to storage until floor done downstairs

**Comment by DeeMcCart** [comment]
![230429 Van with first part of kitchen from Swords (2)](https://github.com/DeeMcCart/DMC_Renovation_Tracker/assets/126502176/208dac6b-1bd5-4fbc-bc15-56438abd4e0b)

**Comment by DeeMcCart** [comment]
![230429 Van with first part of kitchen from Swords (1)](https://github.com/DeeMcCart/DMC_Renovation_Tracker/assets/126502176/29994446-2919-4608-ad17-68c5c04a1593)

**Comment by DeeMcCart** [comment]
![230430 SUN strip laminate floor (5)](https://github.com/DeeMcCart/DMC_Renovation_Tracker/assets/126502176/fb380fd6-211e-436f-ae00-4348e8bfb22d)
